### ISSUE TITLE
problem with file permissions on non-english windows

### ISSUE THREAD

**Issue by graf0** [Webtrends/winrm#4]
System Error Code: 1332
System Error Message: Nie zosta┼éo wykonane mapowanie mi─Ödzy nazwami kont a identyfikatorami zabezpiecze┼ä.

it's from line 31 - you use name 'Everyone', but it's only defined on english-language windows.

**Comment by pcross616** [comment]
fixed. in latest master version.  I will updated cookbook site with version 1.0.2
